"""added image attribute

Revision ID: 334f974e3ab4
Revises: 56ad60bf5ae9
Create Date: 2021-07-09 11:15:31.927265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334f974e3ab4'
down_revision = '56ad60bf5ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
